module.exports = {
    'likes': '{ likes, number } Me gusta',
    'logout':'Salir',
    'english':'Ingles',
    'spanish':'Español',
    'signup.subheading':'Registrate para PsychoPatear a tus amigos',
    'signup.facebook':'Iniciar sesion con Facebook',
    'signup.text':'Iniciar sesion',
    'email':'Correo electrónico',
    'username':'Nombre de usuario',
    'fullname':'Nombre Completo',
    'password':'Contraseña',
    'signup.call-to-action':'Registrate',
    'signup.have-account':'¿Tienes una cuenta?',
    'signin':'Entrar',
    'signin.not-have-account':'¿No tienes una cuenta?',
    'language':'Idioma',
    'upload-picture':'Subir foto',
    'upload':'Subir'
}